### ISSUE TITLE
Droping outside slot make object disappear

### ISSUE THREAD

**Issue by DanSteph1024** [Krsmanovic-S/Complete-Inventory-Documentation#2]
Dear Stefan,

**Bug**

Another small issue: when you drop an object outside a slot, it disappear. You must then close/open the chest to make it reappear on the source inventory.

![Bug_1](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/092dd002-c351-4bc3-973d-126b5eb4e195)

**Information:** 

With your help I was able to get the world coordinate from blueprint and than get an object dropping like Ark (the game). 
Object goes on mouse position if less than 3 meter or drop in front of us if further. I'm very satisfied with it now. 

![image](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/53261c18-958e-4004-9500-0ec35827b115)

 I removed the orientation locking on object and all drop code in blueprint:

End of BeginPlay in ItemActor.cpp
![image](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/137847058/69603cef-0073-4ffe-b212-73ca02d9c09b)

**Request:** 

Transfer with mouse double click and "drop" key like in Ark would be a neat addition to you addon.
Could you give me a direction how to do it ?

Best regards,

Dan

**Comment by Krsmanovic-S** [comment]
Hey Dan, 

thanks for pointing out this as well, I will upload the fix later today but if you want to correct this now I can help. 

> Another small issue: when you drop an object outside a slot, it disappear. You must then close/open the chest to make it reappear on the source inventory.

Inside the **On Mouse Drop** function in the **WGB Inventory**, you just need this part connected to the **Completed** pin on the first for loop:

![Capture](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/927ad217-5cb0-4a83-957e-823d2007b79d)

All it does is check whether we should update the connected inventory UI as well as the one in which the drop occured. This should fix any issue when dropping an item from one inventory onto another in a spot where there is no slot.

> Request: Transfer with mouse double click and "drop" key like in Ark would be a neat addition to you addon.
Could you give me a direction how to do it ?

I've added this to the plugin, both transfering as well as dropping items with RMB. There are a couple of things needed for this so I will post everything one by one. 

Some code changes are needed as well so I will walk you through it. First, change the **AutoEquipItem()** function to return a **bool** instead of being void-type and just return the appropriate values in the function:

![Capture](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/86012281-d4b2-4bf8-9b98-fea51ea7592c)

![Capture1](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/7d77837e-408f-40db-b2e4-e05350814b3d)

The above picture is for the code inside the **AutoEquipItem()** method, we just need it to return true and false appropriatelly. Then we need to slightly modify the code inside the **AddItem()** method:

![Capture2](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/d3bdfdb3-82d6-4e55-ac3a-155e49d6a2a3)

This is all we need in the code, I've noticed an issue with transfers when there is an auto-equip and this here fixes everything. Then we move on to the blueprints:

Create a function in the **BP_Chest** that will serve to connect/unconnect the chest's inventory with the Player:

![connect](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/a14363c3-b1cd-4f2c-8b66-9e9eb7bcf1a2)

You'll need to create this variable called **Unlink Connected Inventories** (by default it should be false). Then we just need to hook this up in the **On Actor Begin/End Overlap** events like so:

![chest](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/8ed83f57-21c4-4d52-9eb8-1577e096908a)

This will set the proper connections between the chest and the player according to if he entered/left the zone of the chest. After this is done we move to the **On Drop** event of the **WGB Inventory**, where we will need to cache the connected inventory variables for the inventory in the widget and the one connected to it prior to the drop:

![cache](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/c36e5641-ccf0-47a1-b3a4-8ee8d9c244a9)

This is to preserve information regarding the connection, as we change this inside the **On Mouse Drop Event** and we don't want that information to overwrite the previous state. Finally, all that is left is to set the transfer/drop inside the **WGB Inventory Slot** like so. For the transfer we go into the **On Mouse Button Double Click** event and add the following:

![a](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/15177029-78ec-4eb0-8d5f-6f4009c5b32f)

And for the dropping we go into the **On Preview Mouse Button Down** event and just include this:

![aa](https://github.com/Krsmanovic-S/Complete-Inventory-Documentation/assets/103185975/49b11089-145a-4982-905b-da1ec1fef8f7)

You should check whether the slot has an item (HeldItem -> Does Item Exist) before the RMB execution, I forgot to add it here

And there it is, this should be all, if something doesn't work please do tell me here and I will try to help. As I said, I will be pushing the update alongside some other quality of life changes later today so when Epic approves it everything will be live.

Regards,

Stefan

**Comment by Krsmanovic-S** [comment]
Just recieved an email from Epic that the update went through so you could just get the updated version!

**Comment by DanSteph1024** [comment]
Hello Stefan,

Just saw your reply, the bug is cleared, thanks !
For the request, I'll stick to your information here because I already modified too much things, thank you very much for the details.

Best regards

Dan
